# Generated by Django 3.2.9 on 2021-11-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='enTitle',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
