# Generated by Django 3.2.9 on 2021-12-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listManager', '0002_attraction_entitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
