# Generated by Django 3.2.9 on 2021-11-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('urlImg', models.URLField()),
                ('attractionType', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('genre', models.ManyToManyField(to='attractionsList.Genre')),
            ],
        ),
    ]
