# Generated by Django 3.2.9 on 2021-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField()),
                ('urlImg', models.URLField()),
                ('attractionType', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='attractionsList.Genre')),
                ('stream', models.ManyToManyField(to='attractionsList.Stream')),
            ],
        ),
    ]
